"""Add is_anonymous field to posts and comments

Revision ID: ca79301cc114
Revises: 5347d634c8bb
Create Date: 2025-05-09 18:20:39.338129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca79301cc114'
down_revision = '5347d634c8bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dev_mate_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_anonymous', sa.Boolean(), nullable=True))

    with op.batch_alter_table('dev_mates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_anonymous', sa.Boolean(), nullable=True))

    with op.batch_alter_table('ps_tip_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_anonymous', sa.Boolean(), nullable=True))

    with op.batch_alter_table('ps_tips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_anonymous', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ps_tips', schema=None) as batch_op:
        batch_op.drop_column('is_anonymous')

    with op.batch_alter_table('ps_tip_answers', schema=None) as batch_op:
        batch_op.drop_column('is_anonymous')

    with op.batch_alter_table('dev_mates', schema=None) as batch_op:
        batch_op.drop_column('is_anonymous')

    with op.batch_alter_table('dev_mate_comments', schema=None) as batch_op:
        batch_op.drop_column('is_anonymous')

    # ### end Alembic commands ###
